/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ExternalInvoiceHeadObjectPageObjectPage journey");

        opaTest("Navigate to ExternalInvoiceHeadObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheExternalInvoiceHeadListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheExternalInvoiceHeadListGenerated.onTable().iCheckRows();
            When.onTheExternalInvoiceHeadListGenerated.onTable().iPressRow(0);

            Then.onTheExternalInvoiceHeadObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheExternalInvoiceHeadObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CompanyCode" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "MessageSequenceNumber" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SequenceNumber" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SalesOrganization" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DistributionChannel" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Division" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SalesOrganizationName" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DistributionChannelName" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DivisionName" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Customer" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CustomerFullName" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "VehRelated" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PostingDate" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProcessID" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProcessIdDescription" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Checkstatus" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CriticalityProcessStatus" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DocType" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DocumentFullName" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SalesDocument" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "InvoiceDocument" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Approver" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ApproverFullName" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ApprovmentStatus" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AmountToBeApproved" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ApprovementText" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CurrencyCode" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ApprovmentGroup" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CreatedBy" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CreatedByFullName" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CreatedAtDate" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CreateAtTime" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ChangedBy" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ChangedAtDate" });
            Then.onTheExternalInvoiceHeadObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ChangedAtTime" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});